name: Go Release Builder

on:
    workflow_dispatch:
    release:
        types: [created]

jobs:
    build:
        name: Build Go
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux]
                goarch: [amd64]

        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@v4

            - name: Extract repository name
              run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "^1.21"

            - name: Build
              env:
                  GOOS: ${{ matrix.goos }}
                  GOARCH: ${{ matrix.goarch }}
              run: |
                  go build -v -o ${{ env.REPO_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }} .  # build and name output file

            - name: Archive production artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ env.REPO_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}
                  path: ./${{ env.REPO_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }} # use the path to your built binary

    upload:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            matrix:
                goos: [linux]
                goarch: [amd64, arm64]

        steps:
            - name: Download a build artifact
              uses: actions/download-artifact@v3
              with:
                  name: ${{ env.REPO_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}

            - name: Upload Release Asset
              if: github.event_name == 'release' # Only run if this workflow was triggered by a release
              uses: softprops/action-gh-release@v1
              with:
                  files: ./${{ env.REPO_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
